require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Ampplex' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment to opt-in to using Flipper
  #
  # if !ENV['CI']
  #   use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  #   post_install do |installer|
  #     flipper_post_install(installer)
  #   end
  # end
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNFirebase', :path => '../node_modules/react-native-firebase'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-masked-view/masked-view'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'RNSmtpMailer', :path => '../node_modules/react-native-smtp-mailer'

  pod 'react-native-fast-video', :path => '../node_modules/react-native-fast-video'

  pod 'react-native-admob', :path => '../node_modules/react-native-admob'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end
